### ISSUE TITLE
Wrong translation for "Play on the board, offline" (IT)

### ISSUE THREAD

**Issue by nyrk** [veloce/lichobile#100]
Wrong translation for "Play on the board, offline"..
Should be: "Gioca sulla scacchiera, disconnesso." << Correct.
instead of: "Il giocatore è uscito dalla partita" << Wrong.

![translation_it](https://cloud.githubusercontent.com/assets/10977136/6168409/6c8cef40-b2c5-11e4-8965-22c43d01a186.png)

**Comment by Evropi** [comment]
I encourage you to submit a new translation through the [translation interface](http://lichess.org/translation/form/it). You may also want to look at other sentences that appear on lichess, since you seem to be competent with language.

It includes help texts beneath each message to show you where they go, tips on how they should be translated, and so on.

**Comment by nyrk** [comment]
Done.
