### ISSUE TITLE
I Hate the New Mobile Update!

### ISSUE THREAD

**Issue by dproctor5** [veloce/lichobile#1030]
Hello,

The new mobile update was pushed to my iPhone XS last night and I had the opportunity to try it out this morning. I hate it. I will admit that some of the menus and game setup menus have improved, but the playing interface looks terrible. 

![C1F0F53B-FAE4-467F-8EAF-4EC44B0D7103](https://user-images.githubusercontent.com/38702740/64958095-51a6fd80-d85c-11e9-895f-61a84b6df2e2.png)

I hate that the move list is at the very top of the screen. I would prefer this to be along the bottom (if at all), or make an option with a button to bring up the moves list. Or, in the settings menu please make an option to show/hide the moves list. I think from a visual perspective it looks awful with the board itself crammed along the bottom of my screen. I much prefer it centered in the middle or along the top. Also, if I need to see the moves list I can easily pull up the analysis board (which I much prefer anyway with the moves list along the bottom).

![1F725478-E867-40A9-AEFE-B121F6B8C964](https://user-images.githubusercontent.com/38702740/64958117-5d92bf80-d85c-11e9-8424-6234b68ffbbe.png)

Personally, I don’t need 5 lines of previous moves. Show me one or two lines discreetly along the bottom. The way this is designed currently is super distracting. It’s so bad that I thought to try the zen mode, which is even worse! Now there’s just a big empty space and the board is still crammed along the bottom!

![BDAE88FD-D2D1-4087-9033-689690073EBF](https://user-images.githubusercontent.com/38702740/64957935-04c32700-d85c-11e9-8058-69f57b756186.png)

Please, I hope this can be resolved. I very much enjoyed the look and feel of the gameplay UI before this update and now I cringe every time I open the app. Just go back to the way you had it before!! If it ain’t broke, don’t fix it! :)

**Comment by ProfessorAbronsius** [comment]
I have to agree, I signed up for github only to leave a comment about this. I hate the new design!!!

**Comment by vvjn** [comment]
Yes, the new design is pretty awful. The old design was working perfectly. Why change something that worked so well? And why make use of an external telemetry using service to just get notifications? This seems like an unnecessary update.

**Comment by veloce** [comment]
I'll make a release that fixes it. It will not go back to the previous design though. Push notifications always used the same service. We just learned later what data it collects. This update makes use of its 'consent require' API to be GDPR compliant.

**Comment by rushhour76** [comment]
Hi guys, I don’t like the new design either - the old was just perfect.
- menu item ‚current games‘ has disappeared
- time display is too big
- cannot see text while trying to write comment because keyboard ‚overlays‘ text window
- marking a game with as favourite ( ⭐️) requires to switch in the analysis section, it used to appear in the game section
- having completed a game, you cannot follow your opponent‘s next match anymore unless this has been completed

**Comment by tuomastiainen** [comment]
This update did bring improvements in the menus, but changing the board location to the bottom of the screen was a mistake. A smartphone is normally held so that the thumb will cover the bottom of the screen. Additionally positions of UI elements should not be changed in apps involving fast reaction, which is the case in the quick games.

Also, the url link option should be added back.

**Comment by dsjoerg** [comment]
One reason to put the board on the bottom is so that it can be comfortably
reached by people who are using the phone one-handed.  Here is an actual
study on the issue: https://alistapart.com/article/how-we-hold-our-gadgets/ .
Also see
https://www.uxmatters.com/mt/archives/2013/02/how-do-users-really-hold-mobile-devices.php

There's a lot to take in there, I only skimmed it.

**Comment by tuomastiainen** [comment]
Well this update moved the board away from the center of the screen where it would be easily accessible with the thumb. Please, try it yourself. In the bottom, the thumb is covering the whole board. At least there should be an option for this.

**Comment by dsjoerg** [comment]
Can anyone demonstrate how the thumb is in the way? I’m not getting it.
How do you use your phone with your thumb in the way?

**Comment by dsjoerg** [comment]
https://imgur.com/gallery/hUw6G08

To demonstrate thumb not in way

**Comment by tuomastiainen** [comment]
The thumb is in the way

https://photos.app.goo.gl/Crjb4GZza7wo8hdU8

The board should be located in the middle of the screen, where it was before the update.

**Comment by dsjoerg** [comment]
Are you also moving the pieces with your thumb?
If the board moves up to where your thumb isn't in the way, then you won't
be able to move your pieces with your thumb.

To permit one-handed use of the app, the board needs to be somewhere that
your thumb can reach.  But I don't see how the board can be within thumb's
reach without also being occluded by the thumb.  The only solution is to
hold the phone with a grip where your thumb can, when needed, move out of
the way.  As illustrated in the picture I supplied.

Or am I missing something?

**Comment by ProfessorAbronsius** [comment]
Another thing that doesn’t work anymore is the chat box. Whenever you try to write something the send button is just greyed out. In fact I believe all aspects of the playing interface have been made worse.

**Comment by rushhour76** [comment]
True, the old interface was just perfect, the new one is a nightmare in every aspect

- menu item ‚current games‘ has disappeared
- Stockfish analysis crashes regularly
- time display is too big
- cannot see text while trying to write comment because keyboard ‚overlays‘ text window
- marking a game as favourite ( ⭐️) requires to switch in the analysis section, it used to appear in the game section
- having completed a game, you cannot follow your opponent‘s next match anymore unless this has been completed
