### ISSUE TITLE
"Return to lichess homepage" leads to webview of the website within the app, and not the native app homepage

### ISSUE THREAD

**Issue by prat8897** [veloce/lichobile#1035]
**I'm submitting a ...** :
- bug report

# Bug report

Current Behaviour: Clicking on "Return to lichess homepage" (situated in this [line of code](https://github.com/ornicar/lila/blob/3d2a4fca65b6134c44634a0e95ab7d4a3adf5ee0/app/views/report/thanks.scala#L49)) returns to lichess homepage inside the webview.

Expected behavior: It should instead quit the webview and return to native app homepage

Steps to reproduce:

0. Open app
1. Visit someone's profile 
2. Click on "Report [username] to moderators" (as per [this line of code](https://github.com/veloce/lichobile/blob/8ff7f89e8ad9a6dc9e9de041e7d01499c2dd2303/src/ui/user/userView.tsx#L297))
3. After reporting, click on the "Return to lichess homepage"

Other information:
The issue for this bug most likely lies in the href written [here](https://github.com/ornicar/lila/blob/3d2a4fca65b6134c44634a0e95ab7d4a3adf5ee0/app/views/report/thanks.scala#L49). The webview goes to the Lichess homepage within the webview. Instead of that, it should detect that this request is made from the app and quit the webview accordingly.

Additionally, the same href has been written in the patron thanks page, and I suspect the same bug can reoccur there. The href in question is situated [here](https://github.com/ornicar/lila/blob/0725765d2084399f6b5f45d3081b4f2ec058f195/app/views/plan/thanks.scala#L67)

**Comment by veloce** [comment]
Sorry but we can't do anything about it. When you report someone to a moderator it opens a browser window with lichess website, so anything you click in that window will happen in lichess website. You could even play a game if you'd like. Those links are here for convenience because the app developer is too lazy to reimplement all the features of the website inside the app. Now when you're done with what you wanted to do in the website, just close the window.
