### ISSUE TITLE
If the move confirmation box is open during player timeout, the UI becomes non-interactable

### ISSUE THREAD

**Issue by MDScar** [veloce/lichobile#1046]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

It seems that a player timeout disables the Move Confirmation modal, but the presence of that modal blocks all other UI elements.

1) Go to game settings => Game Behavior
2) Set move confirmation to always
3) Start a game
4) as game time runs out, begin a move but allow the move confirmation box to stay open
5) allow the game to time out
6) all UI elements become unselectable.

**Expected behavior:**

I'd expect step 6 to look like:
6) Move confirmation box automatically closes and all UI elements respond normally

**Steps to reproduce:**

See above 

**Environment information**

- phone hardware
- phone operating system version
- version of lichess mobile

**Other information:**

Samsung Galaxy 8
Lichess version 6.2.0

**Comment by AdityaMH** [comment]
And then, i must burn the time until time runs out because they fleeing without resign and popup to show claim win or draw now gone.
https://lichess.org/GqXCTGpu
https://lichess.org/VDwihSLz
https://lichess.org/OWdD8gwo

What happen then if i playing classical game (60 minutes for example) and then my opponent fleeing without resign?
