### ISSUE TITLE
Export PGN

### ISSUE THREAD

**Issue by tobiasvl** [veloce/lichobile#106]
The "SHOWPGN" overlay should have an option to export the PGN file, which could simply save the file somewhere and open it, giving the user the option to redirect it to an app of their choice (Stockfish, Dropbox, etc.).

**Comment by veloce** [comment]
We could start by something simpler: copying it to clipboard. Using that plugin: https://github.com/VersoSolutions/CordovaClipboard

I also plan to use it to share game links.

**Comment by frankcalise** [comment]
So I know on Android, sharing with Intents is the preferred method because the user gets to choose which app this content gets pushed to (the OS provides a list based on the content), clipboard being one of them as well.

It looks like this plugin could be interesting? New to using Cordova so not exactly sure how to spot a good one:
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin

**Comment by veloce** [comment]
Yep this plugin looks good. It's more difficult to implement than the copy to clipboard thing. Worth to investigate though. Especially if we can get easily the native share sheet of both platforms.

**Comment by frankcalise** [comment]
Went with your original plugin for now. We can look to do the native share sheets in the future.
