### ISSUE TITLE
Offline analysis not working on puzzless

### ISSUE THREAD

**Issue by mmeyers00** [veloce/lichobile#1063]
**Expected behavior:**

After attempting a puzzle offline it used to load the puzzle in analysis mode to see where I went wrong.

**Current behavior**
It does not load correct FEN, but shows default standard start position.

**Comment by freefal** [comment]
I can't reproduce this. If i put my phone in airplane mode, do a puzzle, and then click on the analysis board, I end up seeing the beginning puzzle position on the analysis board.

Perhaps your phone thinks it has a connection, but then fails to load the position because it's a low-quality connection?

**Comment by mmeyers00** [comment]
Perhaps that's it. I tried that and it worked. When I tested it I was in the subway and lost connection so I figured it wouldn't be a problem since the puzzles also work offline.

**Comment by freefal** [comment]
Ok, thanks. In any case, it would be nice if a failed fetch resulted in
reverting to the offline experience rather than the starting position you
saw (and I have seen). Will see if I can make that happen.
