### ISSUE TITLE
No confirmation of draw offer in app

### ISSUE THREAD

**Issue by kyldvs** [veloce/lichobile#1093]
**I'm submitting a ...**
- bug report

# Bug report

**Current behavior:**

When offering a draw there is no confirmation. My website settings have confirmations turned on (but perhaps the app does not read those settings.)

This is really frustrating when playing a correspondence game, I was trying to navigate to the analysis board and accidentally offered a draw because is in the same menu. Wouldn't be a big deal except it was a  winning position and I can't cancel a draw offer: https://github.com/veloce/lichobile/issues/601

**Expected behavior:**

After clicking "offer draw" there is a second yes/no confirmation check similar to what is done for resignation.

**Steps to reproduce:**

1. Play a game
2. Offer a draw
3. See no confirmation

**Environment information**

- Pixel 2
- Android 10
- Version 6.3.0 (I believe, this is according to App info screen)

**Comment by kyldvs** [comment]
Sorry, I guess this might be considered a feature request not a bug. Depends on if you consider behavior that differs from the site like this a bug :)

**Comment by git-wombat** [comment]
When settings are to ask for confirmation within a game, this should not only be applied to the moves, but also to every game-changing event - especially offering a draw.
So yes, this may be a feature request but I also consider it to be a design bug.
And I would highly appreciate the confirmation for draw offers, since I also sent those offers accidentally every now and then and one time my opponent used this to my disadvantage.
