### ISSUE TITLE
Pawn Promotion Boolean in Analysis Remains After Exiting Dialog

### ISSUE THREAD

**Issue by landry314** [veloce/lichobile#1168]
If you get the pawn promotion dialog in any analysis board in android but you fail to choose the piece and instead hit the back button, you can continue to play the game but the next time you go to any analysis board for any game you will immediately get a pawn promotion dialog that does nothing.

To Reproduce:
1) Open analysis board in any game
2) Move a pawn to the last row
3) When you see the pawn promotion dialog, ignore it
4) Hit the back button in android
5) Open the analysis board again (in ANY game)

You will see the game reset to the current position but the dialog is still there. It will do nothing but force you to choose a piece to continue with the board.

**Comment by maxnordstrom** [comment]
I can add to this issue as it happened in one of my correspondence games.

Apon the pawn promotion dialog instead of choosing a piece I hit the back button (or the the little chessboard icon in the top right, can't remember).

<img src="https://user-images.githubusercontent.com/26596537/110857098-b956d100-82b8-11eb-83d8-a607fb9fee2c.jpg" width="40%" height="40%">

When entering another of my correspondence games I was immediately prompted with the pawn promotion dialog, but now with the color I'm playing in that particular game, and clearly there is no pawn close to being promoted.

<img src="https://user-images.githubusercontent.com/26596537/110857416-1f435880-82b9-11eb-83be-2dfc6c2d5360.jpg" width="40%" height="40%">

When choosing one of the pieces in the pawn promotion dialog I was prompted with the accept move dialog (I have that enabled).

<img src="https://user-images.githubusercontent.com/26596537/110857557-4b5ed980-82b9-11eb-9f5b-cdbbf119d7fa.jpg" width="40%" height="40%">

I didn't confirm my move as I didn't want to mess up my game, so better reproduce this on a dev version.


**To reproduce**
1. In a correspondence game get to the pawn promotion dialog
2. Instead of choosing a piece, hit the back button or the chess icon in the top right
3. Go to another correspondence game.

**Expected behavior**
The pawn promotion dialog should not pop up when entering another correspondence game

**Smartphone**
Device: Sony Xperia X Compact
OS: Android 8.0.0
Lichess app version 7.2.2

**Comment by jas14** [comment]
Can confirm that both in the [online](https://github.com/veloce/lichobile/blob/da67689b83748887d1d5830e08ec8d144706e7b5/src/ui/shared/round/promotion.ts#L7) and [offline](https://github.com/veloce/lichobile/blob/da67689b83748887d1d5830e08ec8d144706e7b5/src/ui/shared/offlineRound/promotion.ts#L16) interfaces, the "promoting" boolean is global and doesn't get reset when switching games.
