### ISSUE TITLE
Disconnect bug

### ISSUE THREAD

**Issue by bruhletmepickausername** [veloce/lichobile#1378]
**White/Black left the game**
Whenever I play on my phone, I am supposed to have 30 minutes to make a move and in those 30 minutes I may need to answer a message, tab out from the app, etc.
Why does this game decide that If I tab onto another app for 1 minute then I left the game? Imagine if that happened on PC, it doesn't make sense.
I honestly don't know if it is a bug or maybe something on my phone settings but I would appreciate any help with this matter because whenever I want to play chess on my phone that's apparently all I can do because the app won't let me tab out without getting disconnected from the game.

**To Reproduce**
1. Go play a game on the mobile app.
2. Tab out for a minute or less.
3. Lose because the game decided to kick you out.
4. See error.

**Expected behavior**
The game counting my 30 minutes properly without kicking me out.

**Smartphone (please complete the following information):**
 - Device: Mi 8
 - OS: MIUI 11.0.5
 - Mobile app.
 - Version: 7.4.0

**Additional context**
Had to create an account here just to post my problem, I apologize in advance if this is not the right place but I'm not very good at these things.

**Comment by LichessUser** [comment]
Same happens with me too

**Comment by jas14** [comment]
This behavior appears to be intentional, and I support the existing behavior.

Suppose your opponent decides they have lost the game 5 minutes into a 30 minute game. They exit the app and go about their day. Now you're stuck waiting 25 minutes until their clock runs out, unable to move on to another game.

I see there could be an argument for adjusting the idle timeout to be proportional to the initial time on the clock, and/or for this behavior not to apply to friendly games, but I don't think that a player should generally be able to quit and leave their opponent hanging.

**Comment by bruhletmepickausername** [comment]
I see your point but I'm still confused because that's not how it works,
you can have multiple games on the phone app running and tab between them.
Therefore you are in no way stuck waiting 25 minutes, you can tab onto
another game til the person makes a move or just doesn't, it actually
shouldn't be that big of a problem 'cause it already works on PC so why not
on your phone.

**Comment by jas14** [comment]
Good point @bruhletmepickausername .

I just did some digging, and it appears that the capability of "forced resignation" is partially dictated [by the server](https://github.com/ornicar/lila/blob/99365fd1706c79c8384da7cba657e8725c410a8e/modules/game/src/main/Game.scala#L375). The capability was only added to Classical-speed games about 10 months ago: https://github.com/ornicar/lila/commit/15c4922c5fe913a5aa41150fb9a0e04e7b4d5531 .

I can't directly find the source issue for that commit. Maybe check out https://github.com/ornicar/lila/issues/5239 ? It might end up coming back to this repo since the mobile app could _theoretically_ keep the connection open in the background...? although we might end up running into technical limitations there.

**Comment by treyhoover** [comment]
This just happened to me in a rapid game as well. Playing on my phone, I tabbed away to answer a message in another app. I tabbed back to lichess 10-15 seconds later and my opponent had claimed victory. If there's not a better way to detect the difference between tabbing away and closing the app, could we at least increase the timeout slightly?

**Comment by veloce** [comment]
Sorry for the delay on this. It will be fixed in the next release.
