### ISSUE TITLE
Puzzle ratings graph shows no data plots. 

### ISSUE THREAD

**Issue by jerweb63** [veloce/lichobile#1494]
Phone hardware: iPhone 11 Pro

Phone operating system version: iOS 14.3

Version of lichess mobile beta: 7.6.0

Steps to reproduce:

Tap icon to display your puzzle rating. 

Description of the observed behavior:

After playing a puzzle, I hit the icon to see my rating and the graph of progress, but only the y-axis is displayed without any data. The numerical rating is given, but the graph and the green and red boxes that show plus or minus points is not rendered. 

Also the number of votes a puzzle has received is not shown, only a zero.  

![DE7E73FF-D7A1-4582-876F-E3E4FA308B7E](https://user-images.githubusercontent.com/8494662/104493477-6375ed80-55d5-11eb-992a-840b9cbd65f8.png)

Description of the expected behavior:

Should be seeing a graphical representation of the ratings progression.

**Comment by redcinelli** [comment]
Phone hardware: OnePlus 8

Phone operating system version: Android 11 / Oxygen OS 11.0.2.2

Version of lichess mobile beta: 7.6.1

Steps to reproduce:

Tap icon to display your puzzle rating.

Description of the observed behavior:

After playing a puzzle, I hit the icon to see my rating but the graph is gone. 
![Screenshot_20210113-201152_86d667449b00b848f46d695606363a65](https://user-images.githubusercontent.com/4200886/104498490-0a5d8800-55dc-11eb-9ee5-f29f3c654b7e.jpg)

**Comment by redcinelli** [comment]
My bad a just checked the release notes for my version of the app.
> removed training rating graph as it's not anymore available server side

@jerweb63 I guess this is why you do not see the graph anymore.

You can see it [here](https://github.com/veloce/lichobile/releases/tag/v7.6.1)

Too bad it was a nice feature.

**Comment by jerweb63** [comment]
Thanks. Yes that is sad, but what can we do? I will just get used to not having it anymore. 

Happy coding!

**Comment by karekaa** [comment]
I do not have any data plots either and «Your puzzle rating: XXXX»  is also frozen, even though several new puzzles has been solved.  I have tried to log out and in again, with no success.  I then tried to remove the Lichess-App altogether. Then after a fresh install again, authentication, which show my old data, my rating was updated again during puzzle solving.  

One possible reason to this «freeze» might be that Isome weeks ago I changed language (on the iPhone, not the app)   from Norwegian setup to English.  These settings was not obeyed by Lichess, since I noted that the Lichess was still in Norwegian mode.  After the fresh re-installation, it went to English as expected. 

It might be a bug, that a change of language for your phone (at least iPhone) will not be detected by the Lichess-App.

I'm having Lichess 7.6.0 (latest version as of this writing) on IOS 14.3 on a iPhone 11 (Model No: MWM02QN/A).
