### ISSUE TITLE
Reconnect update issue

### ISSUE THREAD

**Issue by grantslatton** [veloce/lichobile#153]
The following scenario happened on this game: http://en.lichess.org/wK9bgDIo#38

On my phone, I played 20. Re1

About the same time, I lost connection.

My board (in the app) showed that the move had been played.

Connection was restored but the app said it was my turn (even though the most recent move still showed as 20. Re1)

I tried tapping my rook on e1 and moving it back to e1 or somewhere else but nothing happened.

Upon quitting the app (couldn't continue playing due to the bug), I later went to my laptop and reviewed the game on the website, and it seems the server never even received the 20. Re1 move.

So there seems to be some issue with making a move while having connection problems where the app doesn't display the same game state as the server.

**Comment by veloce** [comment]
What is going on here, is that when you play a move, it is displayed right away. And at the same time the move information is sent to the server. It is done like that because we want the UI to be very fast. Until the server responds and validates your move (which is usually very fast) you are in a intermediate state.

If the network is shitty the server may not receive you move at all and not respond... in that case the app can't know about the current state of the server. When the connection is lost the app is continuously trying to reconnect (when loading circles shows up in the header). But sometimes there is a connection  and still nothing reach the server... I guess this is what happened here. 

In case of bad network there is unfortunately not much to do (the mobile app is using the same websocket logic that has been battle tested on the website), except for showing an alert that says 'poor connection'.
