### ISSUE TITLE
Allow multi-moves premoving

### ISSUE THREAD

**Issue by aldokkani** [veloce/lichobile#1551]
**Is your feature request related to a problem? Please describe.**
You can only premove one move which is not convenient sometimes.

**Describe the solution you'd like**
I would like to implement this myself, allowing players to make multi-able premoves, not sure if there should be a limit or no.

**Comment by papb** [comment]
How would the user use this? How to differ between

* undoing the current placed premove and placing a new premove instead
* adding another premove after the first one

Also how would I premove the same piece twice?

**Comment by aldokkani** [comment]
@papb no need for reinventing the wheel. I tried to see the behavior of other chess apps I couldn't figure how some totally behave but here are some suggestions for your points;

1. double tap anywhere.
2. you just play a move and this will be considered the next move, why would this be a problem?
3. you won't be able to do so unless some changes happen to the current premove behavior (e.g. premoving preview shows a premoved piece on the new square.

**Comment by veloce** [comment]
The problem also is that you cannot do that on the app alone, it has to be a feature for lichess in general (the website as well). So this feature request should be issued in the main repo (ornicar/lila). If the request does not exist already.
So I'm closing it since it's not relevant to discuss that here.
