### ISSUE TITLE
capacitor and stockfish

### ISSUE THREAD

**Issue by Philipp-Sc** [veloce/lichobile#1666]
Hi,

I am working on a chess training app. I use capacitor as well.
Can you refer me to somewhere that shows me how to implement stockfish in my application.

Currently I am only using stockfish.wasm https://github.com/niklasf/stockfish.wasm
Serving the app locally still works fine, though I get the console warnings:

stockfish.worker.js:1 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.

The android app does not start. This is because the SharedArrayBuffer is disabled. Sadly I can not find any way to add/modify the HTTP header to update the Cross-Origin-Policy.

I appreciate your answer, you are clearly very experienced since Lichess is such a wounderful app.

Thanks & best regards,
Philipp

**Comment by veloce** [comment]
Hi,

I developed a capacitor plugin for that: https://github.com/veloce/capacitor-stockfish

I might release it officially some day as a community plugin, but you can already install it from this repository.

I'm closing the issue since it's not the place to ask questions unrelated to lichobile development.

**Comment by Philipp-Sc** [comment]
Thank you @veloce
