### ISSUE TITLE
Add Setting To Display Toast When Game Ends Before Dialog Comes Up (REGRESSION)

### ISSUE THREAD

**Issue by landry314** [veloce/lichobile#1683]
I absolutely hate the way games are ending since the last update. Now, as we are tapping the screen to move, a dialog pops up with options to tap which causes false taps all the time. So many of us are rematching when we don't mean to or hitting "new opponent" and starting new games. What was wrong with a quick toast telling us the game has ended before a dialog pops up?

It is really quite abrupt feeling to have the game end like that. It is awkward, jarring, and causing mistakes. I think it was a bad decision to do this, but, if you like the change then AT LEAST please allow us to go back to the old way. Just add a setting for this. It really disturbs me to be in the chess mindset and then all of the sudden the game is over without a message. A small toast was PERFECT... sigh.

I play a lot of 1-0 and 2-1 games so it is particularly abrupt for me because my mind is moving fast to have the game end so sharply with a black box covering the screen. Bullet players are moving even faster in the last 10 seconds so the chance of false taps is even higher. Also, We play a lot of games in a row so there are many endings. If I were playing one or two 10 minute games it wouldn't be as much of an issue.

This last update was not good for bullet players.

**Comment by JFonS** [comment]
I am having the exact same problem. Many games end up in a false tap as the popup appears in the middle of the game board while playing fast.

Adding some way to disable this would be really nice :)

I will take a look at adding it myself, since I've been wanting to contribute to lichess/lichobile for a while, but I can't promise anything. Any pointers on what needs to be done would be appreciated.

Also, thanks for the great app, I really enjoy it :)

**Comment by veloce** [comment]
I reckon I didn't think it would be a problem for bullet so it's a regression in a way.

New setting should only be added sparingly, so this is not an option here. I'll consider putting back the old behavior in the next release.

**Comment by landry314** [comment]
but why no toast? how does that hurt? it's still a bit abrupt.
