### ISSUE TITLE
New minimalist chess set, still WIP, RFC.

### ISSUE THREAD

**Issue by joaoamaral** [veloce/lichobile#1720]
Hi! I'm a software engineer and designer and I love chess. 

I'm creating a new chess set (tentative name: amaral) to use on lichess that follows the spirit of the "new" logo. It is still work in progress but I would love to contribute.

There is no rush but if possible I would like some feedback on the various alternatives so this is a request for comment/critique. New ideas are welcome as well.

Let me know if this is something you and the rest of the community could be interested in. I can also provide them in SVG and make a PR.

For reference:
King (1,2,3)
Queen (1,2,3)
Rook (1,2)
Bishop (1,2,3)
Knight (1,2,3,4)
Pawn (1,2)

<img width="449" alt="Screen Shot 2021-06-14 at 8 43 39" src="https://user-images.githubusercontent.com/147158/121825675-ba9bfd80-ccee-11eb-8303-15436583a311.png">

Thank you,
Amaral

**Comment by jas14** [comment]
Hi Amaral, the piece sets available on the mobile app are kept in sync with those available on the website - as such, you should open an issue on https://github.com/ornicar/lila first.

Be warned that someone else fairly recently opened [an issue](https://github.com/ornicar/lila/issues/8436) with a new piece set proposal, which was rejected due to the size of the existing set selection.

If your piece set is accepted on lila, please do re-open this issue and we'll be sure to merge it in! You are also welcome to participate in the [lichess community discord](https://discord.gg/lichess), which may be fruitful for feedback.
