### ISSUE TITLE
Tournament type icons (i.e. rapid/blitz/etc.) are missing their icon and just show a colored box

### ISSUE THREAD

**Issue by benediktwerner** [veloce/lichobile#1724]
It's very obvious when viewing the tournaments page.

Most likely caused by ornicar/lila#9136

**Comment by ornicar** [comment]
The problem is that the icon chars are sent along with the tournament data, by lila, to the app. And now they no longer match the icon font file of the app.

I think the next app version should ignore the icon chars sent by lila, and infer its own from the tournament type.

Since we need to support old versions virtually forever, I guess lila will also need to send the historical icon chars to the app.

**Comment by ornicar** [comment]
![Screenshot_2021-06-15-13-57-42-546_org.lichess.mobileapp.jpg](https://user-images.githubusercontent.com/140370/122048570-bc92b900-cde1-11eb-9231-b7b2ed55701a.jpg)

**Comment by ornicar** [comment]
Same thing with correspondence list icons

**Comment by lukhas** [comment]
Coach profiles are broken on the website too: https://lichess.org/@/andresgv36

**Comment by jas14** [comment]
@ornicar not sure what you mean by correspondence list - screenshot?
