### ISSUE TITLE
Ban time starting incorrectly

### ISSUE THREAD

**Issue by Ismael-Schellemberg** [veloce/lichobile#1736]
Recently got banned a few times because i had to leave the game. The ban times have been 1, 2, 3 hours.
Yesterday I had to leave a game and then went to sleep (about 13 hours ago). Right now i opened the game and saw i was banned for 6 hours, so it seems like the ban is fresh starting now, when I'd expect the ban to have been over by now. Now banned for 6 hours which is a ton... Wanted to get a few games.before going to work.

I play on an android phone

**Comment by jas14** [comment]
@Ismael-Schellemberg bans are controlled by the server. Please do re-open this issue if you're seeing a difference between what lichess.org says about your ban time and what the app says about your ban time; otherwise, if you have an issue with ban controls, please open an issue on the server repo, https://github.com/ornicar/lila.
