### ISSUE TITLE
Starting a new game, brief network disconnect, the apps starts two games simultaneously

### ISSUE THREAD

**Issue by csaavedra** [veloce/lichobile#1781]
I reported this first in the lichess feedback forum, but as an afterthought I realized that this might be a bug in the app: https://lichess.org/forum/lichess-feedback/game-completion-97-due-to-lichess-starting-two-games-at-the-same-time

I started a blitz game, the "pairing" screen showed, had a network disconnection, reconnection, the "pairing" screen showed "reconnecting", and then suddenly two games had been started. I focused on one and ignored the other, but this led to me having an aborted game in my history.

I can't be sure if this is a bug in the app, but it looks to me like the app accidentally submitted two requests to start a game to the server (perhaps one before the disconnection and the other after). Of course, I don't know the internals of the app so maybe it's not really a problem with it but the server. Reporting in any case.

**Comment by jas14** [comment]
It seems that there's an unfortunate race condition here.

The setup: we send a `poolIn` (basically "please pair") message every 10 seconds, whether or not the network is considered to be connected. This is in order to ensure the pairing request goes through in adverse conditions, e.g. through a server restart or, _specifically_, a spotty network.

This means that the following sequence of events can occur:
1. The app begins sending `poolIn` requests every 10 seconds.
2. The network connection is interrupted.
3. The server completes the pairing request.
4. The network connection is restored.
5. The app receives the server's "start game" message.
6. The app opens the first game, **but can't cancel sending the next `poolIn` message in time**, so another game is started.

We can't just have the server cancel a match if one is already in play; that would eliminate simul support. Another option would be to automatically end the search when the network goes offline, but that would be an irritating experience for users who switch networks often or have chronically spotty connections.

----- 

I guess one solution could be to suspend the `poolIn` message cycle when disconnecting, and wait a second or so before resuming it after reconnect. Another solution would be to create a unique ID for pairing attempt and send that to the server, so the server could ignore already complete requests - but that requires server work.

**Comment by jas14** [comment]
Thanks to @ornicar who graciously fixed this on the server side in https://github.com/ornicar/lila/commit/bc9473b9b6c148b2f0b77c51872065479ef0049c , I imagine it'll be deployed fairly soon so I'll close this issue.

**Comment by csaavedra** [comment]
Thanks for fixing this @ornicar ! I see that the aborted game is also gone from my list of games. Double thanks!

Another nit though, in my profile (c_saavedra) I still appear with 97% completion even after the aborted game was removed. Is that an issue with how the profile stats are generated or did the removal just not update all stats?

(I know this is unrelated to the mobile app, but I didn't want to open another issue without being sure)
