### ISSUE TITLE
Puzzle major bug on lichess mobile application 

### ISSUE THREAD

**Issue by djsurajguna** [veloce/lichobile#1825]
**This is about a major bug that can found in lots of puzzle that are available in lichess mobile apk**

**To Reproduce**
1. Go to '.Puzzle ..'

**Expected behavior**
This bugs is appear almost every time when the oposite side king is checked with a piece next to it that is not even projected.. every time the oposite king refrain from cutting that piece and try to escape from it even though it is nlt supposed to be.I notice this bug is appeard in lots of puzzles.plewtryto fixthis ...otherwise it affect the quality of the game severely ....
![Screenshot_20210829-191517](https://user-images.githubusercontent.com/86002388/131253139-cea0f7b6-04db-460e-90f7-4b2e9c1f482d.jpg)
![IMG_20210829_193347](https://user-images.githubusercontent.com/86002388/131253210-ef54f5b7-9185-4cf6-a7e2-9b280e2ad0f8.jpg)
As it marked in red this porn can cut the knight easily but it always refrain from it .even though it is harmful for it.please try  to find that kindpuzzles.this                                                      puzzle number is 832809080
**Screenshots**
If applicable, add screenshots to help explain your problem...I attached tge puzzle screen shots...

**Smartphone (please complete the following information):**
 - Device: [e.g.huawei y7 pro]
 - 
 - Version [e.g.7.11.3]
![Screenshot_20210829-191526](https://user-images.githubusercontent.com/86002388/131253116-92edc7d9-d1ad-43e0-9c12-5132d9886ccf.jpg)
.

**Comment by fynsta** [comment]
.... The pawn cannot take the knight because it is pinned by the rook. See [Pin](https://en.wikipedia.org/wiki/Pin_(chess)) on Wikipedia. Especially note the section on [absolute pins](https://en.wikipedia.org/wiki/Pin_(chess)#Absolute_pin):

> An absolute pin is one where the piece shielded by the pinned piece is the king. In this case it is illegal to move the pinned piece out of the line of attack, as that would place one's king in check (see diagram). A piece pinned in this way can still give check or defend another piece from capture by the king.

So... not a bug, that's just the rules of chess. I don't think that "it affect [sic] the quality of the game severely".

**Comment by jas14** [comment]
@djsurajguna I'm not sure I'm understanding your report correctly. If you mean that in the above puzzle, Nf5+ is a bad move because it can be taken by the pawn on e6, this is incorrect because there is a rook on the e file that is pinning the pawn; that is, exf5 would put the black king in check, and is therefore an illegal move.

Please feel free to re-open this issue if that's not the bug you're reporting.
