### ISSUE TITLE
Illegal move of castling when the rook is not on castling position

### ISSUE THREAD

**Issue by emretapci** [veloce/lichobile#1957]
In an analysis of a position, the computer offered castling as an illegal move.

To reproduce, edit the board to position:
2r1k1r1/1Bq2pp1/4pn1p/1p5P/3P2R1/R1pN2P1/2Q1PP2/6K1 b kq - 0 1
Start analysis,
Then play:
1. ... Qxb7 2. Rh4 Qc6 3. Nb4 Qc7 4. Rf4
At this state, the computer offers a King's side castling, even if the King side Rook is on g7.

**Expected behavior**
King's side castling is an illegal move, so it should not be offered.

**Screenshots**
Attached.

**Smartphone:**
 - Device: Xiaomi Redmi Note 8 Pro, Lichess mobile application
![Screenshot_2021-12-22-20-38-55-495_org lichess mobileapp](https://user-images.githubusercontent.com/7909005/147134122-80cf7590-fae6-42da-95f6-169e735b8ebb.jpg)

**Comment by 3TG-3645** [comment]
If the computer says castle is possible... Then this is a 95% the computer is right. What happens here is that castling is a rule that there isn't a thing stated towards position. If none of the rooks in matter or either the king has moved, castling is possible no matter where the rook or the king is. If you want to understand it better, go play Chess960 or Fischer Random. (Chess960 is a chess variant which mixes up the initial pieces.) If in order for white to be able to castle, the rook shall be on A1 square for short-castle or on H1 square for long-castle, and the king shall be on the D1 square so that castling can happen, it basically means Chess960 wouldn't have any sort of castle, since it'd be breaking the standard initial position. The rooks would be no longer on their standard squares, nor the king.

Check out Pam-Krabbé castling. This castle is way too weird to even exist, but it did some time ago. Basically, if there's a rook on the top of the board and a king in the other top, (both of the same colors ofc.) Castling would be possible, this is also the reason some people don't like the castling rule because they say it breaks the fun of chess in some way. The only rule that is stated towards castling position, is due to this weird castle. FIDE has made down a rule that says castle will only be possible, if the rook in matter hasn't moved yet, and if they're in the first line. Otherwise, Castling is illegal. In chess960, castling must be possible. Chess960 teaches that castling can be made on any squares (out of the first line), if the king hasn't moved and the rook hasn't too

**Comment by jas14** [comment]
@3TG-3645, thank you for the very detailed explanation - that is correct. To summarize for @emretapci , or to put it a different way: it is possible in certain variants such as Chess960 to castle when the rook in question isn't on a1 or h1 (or, in Black's case, a8 or h8). The positional notation you've provided, called [Forsyth-Edwards Notation](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation) or FEN, allows us to capture the possibility of capturing in such variants in the third space-separated field:

```
2r1k1r1/1Bq2pp1/4pn1p/1p5P/3P2R1/R1pN2P1/2Q1PP2/6K1 b kq - 0 1
                                                      ^^
```

In this case, `kq` means "Black may castle on the king- or queenside." (`K` means white can castle kingside, `Q` means white can castle queenside, etc.) As such, this is not a bug - it's a feature! :)
