### ISSUE TITLE
Significant battery usage

### ISSUE THREAD

**Issue by b0rysb** [veloce/lichobile#200]
The iOS app consumes about 57% of battery on my iPhone 5S device. Are there any areas of optimisation possible?

**Comment by b0rysb** [comment]
I need to add that this happens during correspondence games with two players, and I use the app only a couple of times a day to perform a move.

**Comment by veloce** [comment]
If you only use the app a couples of time this is not normal. I can think of some optimisations for correspondence games but I doubt it'd make that a difference. 

When you enter a game, the app will disable sleep, so make sure you don't forget it in that state. Otherwise it keeps exchanging data with the server, and that consumes battery.
Can you check lichess data usage in your phone to see if it's correlated?

**Comment by b0rysb** [comment]
Hi,
I am using the app for about a week and I can see it consumed about 1MB of
callular data usage. However, most of the time I'm in WiFi network range.
After making a move I always return to the home screen with iPhone center
button and press the sleep button. I do not leave the app running in the
foreground for a long time, only to make a move a couple of times a day.

Thanks,
Tomasz


2015-09-28 16:07 GMT+02:00 Vincent Velociter <notifications@github.com>:

**Comment by veloce** [comment]
Well, really I don't understand. 

I have the same usage as you: a couple of correspondence games per day, and I don't have the problem.
Normally all data usage is shut down when you put the app in background, and iOS doesn't let any background usage happen. 

Could you try to kill the app every time you finish playing, and tell me if it makes a difference? Thanks.

**Comment by b0rysb** [comment]
Vincent,
When I looked deeper into what's going on, it appeared that I must have
been using the app a little bit more than I thought. Now when there is
Monday and I went to work, and used the app way less than before, the
battery consumption is 23% for the last 24h (47 mins on screen), whereas
for the last 7days it is 36% (7.6h screen).
So it just might be the case that I was not playing a lot, but taking a lot
of time thinking and considering next moves looking at the board.
Let me observe it for a little bit longer to check it my assumptions are
correct.
If so, sorry for the confusions I introduced :)

Thanks,
Tomasz


2015-09-28 18:53 GMT+02:00 Vincent Velociter <notifications@github.com>:

**Comment by veloce** [comment]
https://github.com/veloce/lichobile/commit/0fb87c17639be1709aacc24d2469d646c3d8aaf4

This commit optimize a bit CPU during correspondence games. If you stay a long time searching for best moves it could save a little more battery. It's scheduled with next release (soon), so you'll tell me :)

**Comment by b0rysb** [comment]
That's great. Thank you.

2015-09-28 23:09 GMT+02:00 Vincent Velociter <notifications@github.com>:

**Comment by veloce** [comment]
Another tip: lichess maintains a websocket connection when you're on the game. While it is necessary to play your move, it isn't when you just look at the board to plan your next move. 
Turning network off on your phone and then enable it just to play the move would save a good amount of battery, more than my optimisation will do :)

**Comment by b0rysb** [comment]
That sounds reasonable, but not very practical.

2015-09-30 22:01 GMT+02:00 Vincent Velociter <notifications@github.com>:

**Comment by veloce** [comment]
Yep I agree... unfortunately this is the best you can do if you want to spare battery. And I don't see a way to automate this in the app right now.

**Comment by b0rysb** [comment]
There might be a "Suspend internet connection" button (or sth like that),
but I don't know if it would be highly used (besides me).
Better feature are notifications for correspondence game :)

2015-09-30 22:24 GMT+02:00 Vincent Velociter <notifications@github.com>:

**Comment by veloce** [comment]
I implemented the "suspend connection" setting (in next version) but it works only for puzzles and offline AI sections and all other screens but games and seek.
I don't disable connection during game because it's necessary to play a move and to receive some statuses like takeback offers.

Notifications are planned, we need to work on it, so it will be done. I just can't say when :)

**Comment by veloce** [comment]
Actually when I think about it I could add a button below the board, just for correspondence games, to toggle on/off websocket. 
But the UI is not easy and it's not the most urgent.

**Comment by ornicar** [comment]
I dislike the idea of this button. Perhaps you can just stop sending ping messages in correspondence. This way, there won't be any network activity.

**Comment by veloce** [comment]
Yeah you're right, the button was a bad idea. Stop sending pings is much better, I'm gonna try that.

**Comment by veloce** [comment]
This issue is actually related to this new network setting: https://github.com/veloce/lichobile/blob/2.2.x/project/src/js/ui/settings/network.js
(when it's disabled there is no more default socket on every other pages than games and seek).

I'm not sure this pref is a good idea. It would be best if we transparently optimize network usage to save battery.

Having a longer ping delay would help certainly. The only concern I see is that if you stop sending pings, there is no way to be sure you're still connected, you'd miss for instance a challenge offer and other won't see you as "online".

Still, we may find a ping delay setting (only for default socket) that would still do the job, ie. remain online for others and don't miss challenge. Do you think a ping delay of 30s or 60s would be sufficient for that @ornicar ?

**Comment by ornicar** [comment]
Asking the user is a bad idea.

Lichess will consider you're offline if no ping is received in 10s.

Before we go further, I recommend making measurements of network and battery consumption generated by ping messages.

**Comment by veloce** [comment]
Intuitively I'd say that screen and network consume the most battery, but you're right I should measure it.
I'll create an issue for that.

I'm removing the setting and increasing default socket (and corresp. socket) ping delay from 2 to 6s.

Closing this issue now.
