### ISSUE TITLE
No game start sound

### ISSUE THREAD

**Issue by GrahamJohnson** [veloce/lichobile#224]
In general, the sounds match between browser and mobile (Android), but the game start sound is missing on mobile.  This means if you are seeking a game, you have to stay watching the device to know when a game starts instead of being able to multi-task, or else risk annoying the opponent when you don't realize the game starts and they have to wait or abort while your attention is elsewhere.

**Comment by mattjacobsen** [comment]
+1 and a UI notification would be great

**Comment by veloce** [comment]
Thanks for this suggestion this is a good idea. I could make a local notification also if you think it's useful (same effect as push notification)

**Comment by veloce** [comment]
Actually I answered too quickly: you won't be able to put lichess in background to multi-task while seeking a game. Lichess design requires an open websocket connection to seek a game... which is not possible to have while the app is in background, at least in iOS where background activity is forbidden for most apps (and strictly regulated).

I'm not closing the issue since the sound on game start is still a good idea. And it's good to match website behaviour too.
