### ISSUE TITLE
Implement persistent challenges 

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#274]
TODO: 

- [x] adapt UI
- [x] adapt API
- ...

**Comment by ornicar** [comment]
> Implementation notes

- creation of a challenge uses the same endpoint and form data as before
  - but instead of a game object, it now returns [data about the challenge](https://github.com/ornicar/lila/blob/persistentChallenge/modules/challenge/src/main/JsonView.scala#L15-L17).
- data about a challenge can always be fetched at `/challenge/$id<\w{8}>`, for both challenger user and destination user.
- a list of [all current challenges](https://github.com/ornicar/lila/blob/persistentChallenge/modules/challenge/src/main/JsonView.scala#L11-L13) for current user can be fetched at `/challenge`
- challenges have a versioned socket just like games. Endpoint: `/challenge/$id<\w{8}>/socket/v:apiVersion`
  - realtime challenges (game with clock) must be pinged regularly, by sending a `ping` message to the challenge socket
  - unlimited/correspondence challenges don't need pinging, they stay up for 2 weeks.
  - when you receive a `reload` message on the challenge socket, reload data from `/challenge/$id<\w{8}>`.
- a challenge can be:
  - canceled by the challenger `POST  /challenge/$id<\w{8}>/cancel` (returns nothing)
  - declined by the dest user `POST  /challenge/$id<\w{8}>/decline` (returns nothing)
  - accepted by the dest user `POST  /challenge/$id<\w{8}>/accept` (returns game data)
- on any socket, a `challenges` message can be received, containing a [list of all current challenges](https://github.com/ornicar/lila/blob/persistentChallenge/modules/challenge/src/main/JsonView.scala#L11-L13).

**Comment by ornicar** [comment]
OMG OMG OMG :dancers:

**Comment by JoelMon** [comment]
Can't wait :grinning:

**Comment by freefal** [comment]
Did all these changes get pushed to iTunes and Play Store?
My master, which is synced up to your master, allows me to "Play with a friend" just fine, but when I try to do that in the app from the Play Store, nothing happens.
