### ISSUE TITLE
List friends/follows

### ISSUE THREAD

**Issue by JoelMon** [veloce/lichobile#285]
Now that persistent challenge is a reality we need an easier way to challenge our offline friends. We needs a list of all the players we follow to make challenging them simple.

**Comment by Unihedro** [comment]
http://ja.lichess.org/@/Unihedron/following ?

**Comment by ornicar** [comment]
Joel got a point here.

**Comment by Unihedro** [comment]
I think "recently challenged" user list is also useful, and would help for both desktop and mobile usage.

**Comment by veloce** [comment]
Yes I release a quick version just to make the app compatible with the new challenging API. Now we need to think of the best way to handle challenges. Ideas welcome :)

**Comment by veloce** [comment]
The persistent challenges are for corres games only. We could rethink the correspondence seeks page and integrate challenges in the same page.

With a tab view maybe.

**Comment by JoelMon** [comment]
Maybe the _Player_ list can morph into the _Followers_ list which in turn can also be used to search all players (the magnifying glass searches all accounts). A setup like that would put your friends in the primary position and everyone else in the secondary. I just don't want to have to drill through menus or windows to find my friends, it should be as straightforward as possible.

The Followers list can be sorted alphabetically or by the frequency of play. Not sure which would be better. I like the idea of seeing the players I enjoy playing against on top so not to have to drill through a long list to find them salted among my follow list. What's the average number of followers people have in lichess? Maybe this is a null point.

**Comment by veloce** [comment]
I think instead of *followers* you mean *following*, right? 

You definitely right we miss such a list in the app. Correct me if I'm wrong, but to me it's the equivalent of this page in the website: http://fr.lichess.org/@/veloce/following

Though I agree the current players list is not very useful (it is mainly for searching players), I'd prefer not to mix friends in that. Firstly because it would not be clear, secondly because it think another link in the menu makes more sense. 

I see it as a replacement for current 'online friends' entry in the side menu, under profile. As in the website now you access your friends from your profile links. The advantage in doing that is also that I can reuse translations of the website. It may appear trivial but translation is a huge work.

Actually let's do this as in the website: 2 links, one for following, one for followers.

What do you think?

**Comment by JoelMon** [comment]
@veloce yeah, _Following_ is what I meant.

When I say morphing the _Players_ list in the _Following_ list I don't mean having a window that lists the people I follow and online players at the same time. I meant that from within the _Following_ window I can choose to see/search all players if I choose by clicking an icon. Now that I say this, it seems cumbersome.
