### ISSUE TITLE
[Android] Most notifications are never created

### ISSUE THREAD

**Issue by danarnold** [veloce/lichobile#312]
There is no app killer or anything running. The app just doesn't like to give notifications on Android.

Phone is Nexus 6P, stock Android 6.0.1 MHC19I.

**Comment by veloce** [comment]
There is not enough description so I can know your problem. To me notifications are working well since I receive all expected notifications. What is unclear for you maybe is when you receive notifications. Let me clarify this:

* when your opponent makes a move in a correspondence game
* when a correspondence game ends
* when you receive a correspondence challenge

That's all. Be aware also that currently push notifications do not work on multi device. It means you'll receive the notif on the last device that has registered.

**Comment by danarnold** [comment]
I apologize for the lack of information, but I'd be happy to give you any information you need to help diagnose the issue.

I've experienced this when playing correspondence games. I only receive notifications when my opponent moves within a very short amount of time after I've moved. The same goes for if a game ends, or if I get a challenge; unless I've been on the app in the last hour or so, it doesn't give me a notification at all.

I'm not sure what you mean by "the last device that has registered." Does the website count as a device? So, would I be correct in assuming that if I visit the website after I've used the mobile app, then I won't get notifications on mobile when I've opened the website more recently? Or is it only between multiple Android/iOS devices that this conflict occurs?

**Comment by veloce** [comment]
No, the website doesn't count as a device. 

To receive the notification you must be away from the game. That is, if you have an open tab with the game, you won't receive the notification.

**Comment by danarnold** [comment]
OK, I understand. I only have one mobile device, so that shouldn't have been the issue, then. I definitely did not have a browser tab open when I didn't receive notifications.

**Comment by jclusso** [comment]
I have the exact same issue on iOS. I have never received a single notifications for anything including game invites or moves and I never have had the website open.
