### ISSUE TITLE
Copy PGN to clipboard should include player tags/date/result/etc

### ISSUE THREAD

**Issue by dfc** [veloce/lichobile#321]
The pgn that is copied to the clipboard is missing a lot of metadata. Can the rest of the game data be added to the pgn tags?

**Comment by veloce** [comment]
Can you be more precise, plz. It is for online games or offline games?

**Comment by dfc** [comment]
Android Repro steps:

1.  Play online game.
2.  After completion, select go to analysis board.
3.  Advance to last move (see #334)
4.  Touch share button.
5. Select share PGN
6.  Select copy PGN to clipboard.
7.  Paste copied pgn

The pasted PGN is missing lots of metadata in the PGN tags:

* Player names
* ELOs
* ECO
* Termination
* etc

If you view an old game by going into your profile and selecting a past game this data is correctly copied.

**Comment by veloce** [comment]
Ok thanks for the report. The issue is that PGN of analysis is currently a 'real time' PGN that is generated based on current position on board (and move history).

This is not the behavior in the website, so I will change it accordingly. It means that if you explore variations from a game analysis you won't have them in the pgn.

It will still be the behavior in empty analysis board, just like in the website.
