### ISSUE TITLE
puzzle feedback on failed puzzle

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#504]
When solving puzzles as a registered user, the experience seems to have degraded (got a lot of complaints about it).

For instance after failing a puzzle, here's the screen I see:

![](https://i.imgur.com/qJuhlm6.png)

I don't know how it was before. But there isn't much info (rating, rating diff) or call to actions (retry, next puzzle).

**Comment by leekaiinthesky** [comment]
I do puzzles in the app often and love the experience. I agree that something small changed relatively recently. Just to give some information on its past behavior:

If you solve successfully on the first try:
- Victory text
- See the rating of the puzzle
- Your rating update diff

If you fail on the first try:
- Failure text
- See the rating of the puzzle
- Your rating update diff

If it's not your first try:
- Victory/failure text
- See the rating of the puzzle
- No rating update diff

But in the latest behavior:

Same as above, except no rating update diff in any circumstances. So my first reaction as a user was maybe I was having network issues, or maybe somehow the app was always thinking it was my second try instead of my first. I didn't realize others were having this issue until I saw this on GitHub. It would be good to fix this bug and restore the original behavior.

Regarding potential enhancements mentioned by @ornicar, as someone who has used the app to do puzzles for a while now, I no longer have feelings about these, but:

- Viewing your rating. It is possible to view this by tapping the ellipsis icon or using the device in landscape mode. Perhaps visibility could be improved.

- Calls to action. There never have been these. The circular return arrow button lets you retry, and the play triangle button advances to the next puzzle, but it's possible that some text could be useful here.

I do have one other enhancement wish regarding the puzzles, but I think it is more a lichess request and not lichobile:

- I wish you could go back and see the history of past puzzles! For example, if I remember I did a really good one three puzzles ago and want to share it with friends, I don't think lichess gives me a way to find it. It could be nice if there is somewhere I could view a puzzle history feed.

Thank you both for the terrific apps.

**Comment by veloce** [comment]
So, to sum up the missing rating diff is the only thing that changed recently. @ornicar I guess it's a small BC break here and I guess you could add it back to the puzzle API?

Regarding puzzle user interface, there is certainly place for improvement. I know it's a work in progress on website, I'll probably try to do the same and if possible take into account the suggestions above. 

One thing though: it's difficult to add text for actions on a tiny screen, especially when the app is translated is more than 30 languages and the original translations are meant for desktop display. My strategy so far has been to use icons with text hint showing as a toast message triggering on long press. It think, but I can be wrong, that people accustomed to smart phones would tend to try long press as it's king of a widespread behaviour. 

If I want to improve on that side I'd certainly need the help from a real UI/UX designer.

**Comment by ornicar** [comment]
I'm looking into adding back the missing data.

**Comment by leekaiinthesky** [comment]
I forgot to include "time to solve" (if success), but it looks like you remembered.

**Comment by veloce** [comment]
Still missing: 

- [ ] ability to revert just the move for already failed puzzles
