### ISSUE TITLE
iOS sound volume not adjustable

### ISSUE THREAD

**Issue by lightbulbjim** [veloce/lichobile#520]
If I enable sound in the lichess settings then it's always at a loud volume. It does respect the ring/silence switch, but the volume should also change with the system volume control. I'm running lichess 4.8.0 and iOS 10.2 on an iPhone SE.

**Comment by lightbulbjim** [comment]
I should mentioned that I tested on Android and the volume control was working as expected. So this is an iOS problem only.

**Comment by lightbulbjim** [comment]
I just upgraded to 4.10.1 on iOS 10.2.1 and this problem is still occurring.

**Comment by pianowow** [comment]
I have noticed this issue as well.  There are (at least) two volume levels in iOS, one for the alarm and ringtone, and another for system/music/sound effects.  I believe the correct one to follow is the latter.

**Comment by lightbulbjim** [comment]
Just to clarify, this is in-game sounds which should be adjustable. Notification sounds are being handled correctly.

**Comment by TheSIlentLink** [comment]
I also have this issue and makes using the app very annoying. Please may he have a fix. It has been happening for months now...

**Comment by TheSIlentLink** [comment]
Still not adjustable on lichess 4.15.0

**Comment by veloce** [comment]
The sounds are played with ios [SystemSoundService](https://developer.apple.com/documentation/audiotoolbox/system_sound_services) and this is the proper way to play sound FX on ios according to all documentation I could find.

The small drawback is that those sounds are tied to the system volume, but this is not an issue if you go to your phone's 'Settings' -> 'Sounds', in section 'Ringer and alerts': enable 'Change with Buttons'.

Playing sound effects with audio (music) volume instead require using the regular audio player which has overhead since it's meant to play longer sound.
