### ISSUE TITLE
Searching game problems

### ISSUE THREAD

**Issue by fabio656** [veloce/lichobile#614]
Hi!
i have a problem with the searching games, in my case using "quick games".
Very often i click, for example, 5+3 game and the app search the opponent for a lot of time.
It seems that the app did not find opponents, but for true, it find them and 2-3-4 games starts IN BACKGROUND but the 5+3 search dont stops.....and i am forced to stop the search and abort 2-3-4 started games so i can play only 1 game.

The problem is that all this aborts ruin my profile "completion rate" and seems that i abort a lot of games

Sorry for my bad english, i hope you undesrtand.

**Comment by veloce** [comment]
Thanks for the report. 

Can you precise from what app version have you started to see the problem?

**Comment by fabio656** [comment]
I noticed this issue with the last 2-3 updates...not only the last version.

No, sorry...i cant reproduce the bug step by step....ii seems like a random bug...
Sometime it happen 2 time in a row ...but sometime don't happen for 3-4 days....

It is very strange

**Comment by Lahmy1** [comment]
Hello,

today i got the same issue with the version 6.0.0. I started 8 games in the background while still searching for 2+1 games via quick games menu. And i got timed out for that :(
In my case it might be due to an instable internet connection. 
Just wanted to let you now that this problem is still there.

Thanks in advance
