### ISSUE TITLE
Offline computer game is suddenly extremely difficult even in level 1

### ISSUE THREAD

**Issue by jonromero** [veloce/lichobile#630]
It seems that the level of the computer when you play offline is **way** higher that it supposed to be. 
I noticed this change six months ago (same as other users: https://www.reddit.com/r/chess/comments/6qljpp/is_the_offline_computer_way_stronger_than_the/).

Maybe a wrong setting on the stockfish engine?

Level 1 when you play offline is something like Level 5 or 6 when you play "with the machine" making it very difficult for new users to play.

**Comment by Pluckerpluck** [comment]
I too have had this problem for some time now, though I don't remember when it started. I went from being able to win with ease to losing constantly.

I posted a forum post about it as well:

https://lichess.org/forum/lichess-feedback/android-app--the-cpu-difficulty-insanely-high

Just look at the game I posted in that. Stockfish 1 vs Analysis. I chose an opening that had less trading to keep as many pieces on the board for as long as possible and this lvl 1 bot that should only be looking 1 move ahead didn't make a mistake until move 34. Something is horribly wrong.

I can't see anything wrong in the code though, so I'm worried it's a Stockfish bug or something. I can only assume depth is completely ignored...

--------------------

Side note: When playing against AI does it make sense to use all cores? If you're fixing move time as well as depth doesn't it make more sense to limit to 1 core to get a more consistent experience over different hardware.

**Comment by Pluckerpluck** [comment]
Just wanted to say thanks so much for fixing this! I shall patiently wait for this to go live. I've been missing playing all the chess variants while on the go. As much as I like them, they really aren't that fun when you never win against the lvl 1 computer.

**Comment by veloce** [comment]
Yeah, sorry for having taken a long time to fix it. It was just a compiler flag to enable (previous version didn't require it).

Stockfish level 1 should be even less strong now.

**Comment by jonromero** [comment]
A thousand thanks again! It was driving me crazy!

**Comment by ThibaultMndr** [comment]
It seems there is a regression with this issue. Playing fully offline against Stockfish level 1 is very harder than playing an "online with the computer" friendly game, also with Stockfish level 1. The "online computer" makes mistakes as expected for the first level of an engine, but the "fully offline level 1" is very hard to beat

(tested on ios)

**Comment by Pluckerpluck** [comment]
Trying this out again myself on Android, I can say that the Stockfish level 1 at least still makes some completely stupid mistakes (tested offline). It primarily has a habit of just not capturing pieces when able to. Simply choosing to trade often finds you up a piece because they retreat. 

I can't say that offline stockfish level 1 isn't harder than the "Online with a computer" , but I can say that it's nothing even close to what it was before the fix.

**Comment by ThibaultMndr** [comment]
I have been able to test on Android, and the offline computer at level 1 seems weaker, making stupid mistakes as Pluckerpluck described. Today I won a match against Stockfish 1 on Android, but on ios I wasn't able to win anything since I am playing lichess. I don't know if it is an ios specific bug/regression, or if it is the computing power gap between an old Android tablet and my more powerful iphone SE (1st gen)

**Comment by veloce** [comment]
Sorry that's a regression, only on iOS. Will be fixed in next release.

**Comment by ThibaultMndr** [comment]
Thanks !

**Comment by shev72** [comment]
I have the latest version on iOS and the issue still exists.  Stockfish is way too strong on level
