### ISSUE TITLE
Switch to crowdin translations

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#639]

**Comment by jas14** [comment]
Hey @veloce, can I pitch in here?

**Comment by veloce** [comment]
Hi @jas14, of course! That's not a trivial change tough. You should contact @ornicar as well because it will probably require some synchro work with the main lichess repo (ornicar/lila).

**Comment by jas14** [comment]
Hey @ornicar, any thoughts on how to get this started? Should/can we create a new project in the lichess Crowdin org, piggyback off the existing project, or would you rather thid be completely separate?

@veloce, I'm thinking of pulling in a JS i18n library instead of the current manual solution, probably i18next. Any opinions or thoughts on that?

**Comment by jas14** [comment]
ping @ornicar

**Comment by veloce** [comment]
@jas14 as for the i18n library I'd rather not use it and stick to a manual solution that you can update of course. 

You can perhaps take the lila module and use it in the app:
https://github.com/ornicar/lila/blob/master/ui/site/src/standalones/trans.js

Only a couple of functions, easy to understand, and all are useful. Much less code than a whole library.

**Comment by ornicar** [comment]
I can now create a new open source project but "lichobile" is already taken - by you, I think https://crowdin.com/project/lichobile

**Comment by jas14** [comment]
@ornicar I did start that project to test it out, if we go with this option I'll invite you to manage it too.

But, if we do start this separate project, the translations and original strings will diverge from the lila project. Are we concerned about divergence?

The alternative is for me to write a script that downloads the translated XML files from the lila project and convert those into JSON (dealing with plurals somehow). The downside is that we won't be able to handle any strings that are in the lichobile but not lila - there's already a blob of those in app.js.

If nobody objects, I'll submit a PR for the diverging option.

**Comment by superuser-does** [comment]
Hi @jas14, I see one of our contributors found your Crowdin project on their own accord. Most of the strings are currently duplicated between the site and your project.

So to prevent duplication of effort for translators, I think it would be best to continue as we currently have and put them all into the main file (`site.xml`) if they affect both. We can split off any strings that are used only for lichobile (there are none that I'm aware of personally) into a separate file but under the same project. I think translators can reasonably expect it as this is the _official_ Lichess mobile app.

Thoughts @veloce and @ornicar (cc @niklasf)?

**Comment by niklasf** [comment]
Both options (seperate project or same project) seem reasonable.

Something to be aware of: There can only be one GitHub integration per project, I believe. So when using the same project, pull requests for adding strings would have to go to https://github.com/ornicar/lila. And translations would have to be downloaded with a script from the API, instead of receiving automated pull requests.

**Comment by jas14** [comment]
@superuser-does yeah, that string duplication was one reason I decided to abandon that method. All the attribution for the "initial" translations would have also gone to me, which wasn't right.

@niklasf, when I was looking into this, it looked like lichobile had lost synchronization capabilities with lila. It had previously been [pulling from lila via web](https://github.com/veloce/lichobile/blob/master/scripts/i18n-fetch), but lila no longer serves that asset. So, the last update to translations was in March. Is there a different API we can use to fetch translations? Otherwise, I can look into transforming the XML into a flat JSON structure the way lila does when injecting the translation blob into pages it serves.
