### ISSUE TITLE
the app overrides the user preferred language

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#744]
Initially reported on https://github.com/ornicar/lila/issues/3907

- let's assume your phone is in english
- go to lichess.org in a browser and select another language (say, french, for instance)
- the new user language (french) is saved in lichess server database
- open the app again
- now the user language is set to english, without the user manually requesting so
- go to lichess.org in a browser, language is set to english. It should remain at "french".

The app should honor the server-stored language, and if none is set, default to the phone language.
It should not just send to the server the default phone language.

**Comment by freefal** [comment]
I think the offending line of code is here: https://github.com/veloce/lichobile/blob/master/src/main.ts#L119

**Comment by veloce** [comment]
It's been here for a long time and the original intent was to set server lang in order to have server translated content in the same lang as the app and _not_ to set the server lang _preference_.

Of course, the right way to fix this is to honor the server-stored language. But we need to be careful because the server does not have the exact same languages as the app.
