### ISSUE TITLE
Training Puzzle does not synch with webpage

### ISSUE THREAD

**Issue by GiHutb** [veloce/lichobile#831]
# Bug report

1) Solve Learn/Puzzles (macOS Chrome) 
https://lichess.org/training/#puzzleid1# to
https://lichess.org/training/#puzzleid20#  and finish solving on Desktop.
2) Open iOS LiChess app and from the hamburger menu click training and it starts from 
https://lichess.org/training/#puzzleid1# again and continue with same puzzle order.

For example, if you solve 45 puzzle in desktop you have to solve all those 45 puzzles again in order to solve a fresh/unseen puzzle. In this process there will be no puzzle rating gain or drop. 

**Expected behavior:**

When I solve puzzles from Desktop and then when I switch to iOS app it should synchronize and let me continue to solve puzzles.

- phone hardware iphone 7  also seen on Android
- phone operating system version iOS 11.3
- version of lichess mobile 5.6.1

**Comment by GiHutb** [comment]
I think https://github.com/veloce/lichobile/blob/master/src/ui/training/offlineService.ts

function syncPuzzles is problematic.

**Comment by MannyC** [comment]
This is happening for me too

**Comment by bakkegaard** [comment]
Is this problem solved @veloce?

**Comment by luismbo** [comment]
I've just updated to 6.0.1, and although the puzzles don't seem to be in sync (which is probably OK, except it doesn't allow the user to continue where he left off from the desktop), it doesn't show repeated puzzles. The rating also seems to be properly updated. (Thanks!)

**Comment by cmzeno** [comment]
Dear Development Team,

There are dozens of reports that the Android mobile application does not update the puzzle score. 
Moreover, it brings up older puzzles out of millions available, so it seems to be out of sync (just a wild guess). The desktop version though is flawless!

In spite of receiving a series of reports, you seem to have choosen to disregard those as irreproducible. Some similar threads/topics have been simply closed with little if any justification.  You are however partially right. The bug is SPORADIC, alas more frequent than working. 
In my case it is reproducible almost all the time.

Anyway, if a bug cannot be reproduced right away, that doesn't mean you automatically have to dismiss it, esepecially since so many reported it. 
This defect in my case spoils much of the fun. Please please please look into it. Thank you in advance, for I trust you will have it fixed it in the next release....

**Comment by luismbo** [comment]
@cmzeno have you tried version 6.0.1? Seems to be fixed there.

**Comment by cmzeno** [comment]
Dear Mr. Oliviera,

I believe my app is up to date. I will however uninstall the current
version and reinstall the latest from the app store (clean). Then verify
again and get back with an answer as soon as I manage to test it properly.
Sorry for the late answer. I am having some tough days myself, struggling
with implementation of my own software in the office, like crazy...
Please allow me to sincerely congratulate you for the best chess
"enterprise" software available to us, chess lovers!
Greetings,
Zeno

**Comment by KommX** [comment]
@cmzeno Try to clear you app data.
This did the trick for me after the update to version 6.0.0, see #838.

**Comment by cmzeno** [comment]
Hello Lichess friends, Mr. Oliviera,

I deinstalled the application checked for leftovers, removed those as well (although those folders were empty). Sadly even after reinstalling it clean, it still does not work.
What happened was following:

I tried to do some chess puzzles, which I miserably failed (2 AM is not the best time for puzzles) thus involuntarily decreasing my strenght towards 2178 roughly. As I reinstalled the application serveral times, the rating is still the one I had several days ago, around 2220+. 

Bottom line:
1. The bug seems not to be fixed in version 6.0.1.
2. It turned to be sporadic, although I my case it now became constant.
3. Clearing Cache, Data and whatever folder, along with uninstalling the app does not do the trick. At least not on my hardware, which is an older LG G3 D855 (I'm more conservative and don't keep up with harware progress and trends unless really necessary).

Unfortunately I have absolutely no knowledge of Android development, sorry (I am mostly living in a wolrld of Windows). Please let me know if there are any files, logs or some data possibly holding "evidence" of the defect, and I will gladly attach those for a "post mortem". 

Thank you again and let me know if there is a way I can help nailing this pesky bug...
Regards,
Zeno

**Comment by Sinket** [comment]
The bug still reproduces on Android in v6.1.0 (Device is Google Pixel Android version - 9)

**Comment by jozeng** [comment]
Still occurring as of Nov. 15 on the Android app.

**Comment by cmzeno** [comment]
I decided to use other apps or online puzzles. There are so many that you
can easily skip this one without loosing anything. Sure, it would have been
nice if this feature had worked, but you can't force the development team
to exceed their competence. They just reached their limits and are unable
to find the error.
And they also closed the thread... Lovely. So this one is officially a
"cold case".
Greetings,
Zeno

On Jan 2, 2019 at 11:25, <Ollie Campbell <notifications@github.com>> wrote:

This is still happening for me (and has been for months). It essentially
makes the puzzles useless on iOS, since I have to re-solve dozens to ever
see a new one.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/veloce/lichobile/issues/831#issuecomment-450817263>,
or mute
the thread
