### ISSUE TITLE
BUG :  training rating , graph and red/green squares are stuck and don't sync with website

### ISSUE THREAD

**Issue by Dharaig** [veloce/lichobile#838]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

My rating graph in training is stuck on 1542.  The colored squares  below the graph (red  and green) don't update and don't sync with lichess website.

**Environment information**

- Phone Asus zenfone 2 deluxe
- android version 5.0
- lichess v5.6.1

**Comment by KommX** [comment]
I have the same problem. Maybe it's related to https://github.com/ornicar/lila/issues/4317.

**Comment by apunko** [comment]
Hello, @veloce!
Do you plan to work on the issue in the nearest future? I can try to fix if you have some other work to do.

**Comment by veloce** [comment]
You can try, but it seems to be more a server issue, which belong to ornicar/lila then.

**Comment by veloce** [comment]
Ok, now I tested again and I see the error too (last time I checked I had no issue). So I can investigate.

**Comment by wmhopkins** [comment]
I'm also seeing this, Pixel 2 XL with latest version of lichess app. The problem started several weeks ago, but can't say for sure exactly when, or with which app version.

Symptoms:
- Score stuck; never updates
- Red/green score boxes do update, but _the last box never updates_. Instead, each new box appears as the second-to-last box, and the first box drops off, while the last box never changes.
- The graph does update, to match the (incorrect) series of boxes below, but the update is delayed. The boxes update immediately whenever there's a new score, but the graph stays stuck. If I restart the app or go to the menu to re-select "Training", the graph is updated. Can't say definitively what happens if I win and hit the button to choose the next training puzzle; don't have time now to run that experiment.

One possibly relevant bit of information (since this looks like an off-by-one error): My usual habit is to start playing with the puzzle of the day, _which doesn't get scored_, and then continue playing by hitting the "next" button after solving the puzzle, which then takes me to "Training" without having to go through the menu to get there.

**Comment by manuelfedele** [comment]
Just a report.
Environment:

- Huawei P20Pro
- Android 8.1.0, April 1, 2018 security patch level
- Lichess App version 5.6.1

**Bug**: Training score stuck on mobile app.

Dummy steps to reproduce:
- [**web**] Training score: **1637**
- [**mobile**] Open Lichess Mobile App -> Training
- [**mobile**] Click on "three dots" (bottom left). Score: **1629**
- [**mobile**] Complete an exercise correctly (_by the way, it's the SAME as the last exercise I played correctly on the web app, maybe this can help_).
- [**mobile**] Click on the tree dots. Score: **1637**
- [**web**] Training score: **1637**
- [**web**] Complete an exercise correctly. Score: **1647**
- [**mobile**] Refresh the app. Click on "three dots". Score: **1637**
- [**mobile**] Fail an exercise (_this time was NOT the same as the last played on the web app_)
- [**mobile**] Click on "three dots". Score: **1637**
- [**web**]. Score: **1632**

**Comment by veloce** [comment]
Bug has been found. It's a regression caused by a server side change. An update has been made to the client to fix the issue; I'm currently testing it and a release is planned soon.

**Comment by KommX** [comment]
As far as I can see this issue and #4317 are not solved in version 6.0.0, are they?

**Comment by veloce** [comment]
It is solved normally. Try to clear you app data.

**Comment by KommX** [comment]
Thank you @veloce !
That did the trick for me.
