### ISSUE TITLE
'Flip board' button in study mode

### ISSUE THREAD

**Issue by Allirey** [veloce/lichobile#848]
It doesn't exist, should be implemented

**Comment by ChristianBraeunlich** [comment]
Glad I used the filter to search for exactly this feature.
I think this would be an excellent feature, since I recently found out that the button is simply not there, when I needed it "most" ;-) - simply copying the pgn and importing it as a new game was the work-around for me.

- "Flip Board"-Button in Study

I use the v6.3.0 App on iOS.
