### ISSUE TITLE
Lichess Android App can't connect to the server when a match is opened

### ISSUE THREAD

**Issue by ghost** [veloce/lichobile#875]
**I'm submitting a bug report**

# Bug report
**Current behavior:**
The Lichess Android App can't connect when opening a new or current match match. I'm able to open current games (and see the latest move) and start new match, but my moves don't get send to the lichens server. The app shows current player stats on "Home" and Puzzles are working fine. The App shows the Ping and Sever response time on "Home" but only displays "?" when a match is opened. Playing in the browser version works fine.

**Expected behavior:**
I should be able to make moves.

**Steps to reproduce:**
Unknown. The problem occurs all the time and I don't know what triggered it.

**Environment information**
- Smartisan T2
- Android 5.1.1 (Smartisan OS v4.2.5)
- Lichess mobile: 6.0.4

**Other information:**
I already tried reinstalling the app and logging out and back in, but that didn't fix my problem. The problem occurred about a month ago. I saw multiple similar posts on the Lichess forum, but didn't find a bug request in here.

Screenshot:
![screenshot_2018-07-12-20-02-03-427_lichess](https://user-images.githubusercontent.com/4144911/42651795-c0129846-8610-11e8-990f-04fcbff663dc.png)

**Comment by qazip** [comment]
Same issue here..

**Comment by AdrnF** [comment]
Which Android version are you using?

Similar bug reports ([here](https://lichess.org/forum/lichess-feedback/bug-mobile-app-scroll-not-working-on-android) or [here](https://lichess.org/qa/466/mobile-app-v20--failing-to-recognize-internet-connection)) suggest that the problem is related to an outdated WebView version on older Android devices. Usually WebView is updated with the Chrome app, but you could try updating it manually [here](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en). It didn't fix the problem for me, but maybe it works on your device.

**Comment by qazip** [comment]
I am using android 5.0.2.

**Comment by qazip** [comment]
@AdrnF , thank you for the comment. Updating android system webview fixed the issue for me.
