### ISSUE TITLE
[Bug report] Cannot load theme file

### ISSUE THREAD

**Issue by renyhp** [veloce/lichobile#902]
Whenever I try to switch to a theme (apart from Dark and Light), a progress bar is shown and, after it completes, a toast is shown saying "Cannot load theme file". [GIF](https://imgur.com/a/cYhyozT)

**Environment information**
Huawei P9 Lite (VNS-L31C432B413)
Android 7.0
Lichess v6.0.4

**Comment by freefal** [comment]
Confirmed. We'll take a look...

**Comment by Ilis** [comment]
Theme loaded but selection remains on default theme.

v6.1.0 on Android 9.

**Comment by freefal** [comment]
I've been trying to debug this issue unsuccessfully. To memorialize what I've learned...

The download of the image succeeds. I can see the blob's size and the XMLHttpRequest's status code is `200`. But when we try to write it, there is a "JSON Error" that gets generated.
One would think it was an issue with the filesystem. Except, when you change this line (https://github.com/veloce/lichobile/blob/master/src/utils/filesystem.ts#L64) so that the blob being written is just a constant rather than the response, it works fine and can be read back. For example, changing that line to `const blob = new Blob(["Meow"], { type: "text/plain" });` works great.
The only thing I can think of is some quota issue, but I have no idea how to debug it.

**Comment by renyhp** [comment]
If that's of any help, the issue has disappeared on my phone some time ago.

**Comment by superuser-does** [comment]
I have just discovered the feature and I have this issue. Like the OP, the download completes for me and is followed by the same error message.

Samsung Galaxy A3 2016
Android 7.0
Android System WebView 74.0.3729.112
Lichess v6.1.2 (latest from the Play Store)

**Comment by freefal** [comment]
Thanks for the report. @veloce and I have spent hours trying to debug this
issue to no avail. There is some underlying quota issue with file storage,
but the errors (`JSON error`) are so vague that its practically impossible
to debug. I'm not hopeful that we're going to be able to fix this soon.

**Comment by definitelynobody** [comment]
I also have this issue. I have never been able to change themes.

Android 7.1.1

**Comment by veloce** [comment]
Fixed in 2c0d7477c92 (by rollbacking to the plugin solution).
