### ISSUE TITLE
Puzzle chart and ranking is not updated

### ISSUE THREAD

**Issue by ChameleonRed** [veloce/lichobile#906]
**I'm submitting a bug report.**

# Bug report

1. I do puzzle.
2. I click chart.
3. Ranking and chart **is not updated**.

**Chart and ranking should be updated.**

**Steps to reproduce:**

1. I do puzzle.
2. I click chart.
3. Ranking and chart **is not updated**.

**Environment information**

- phone hardware: Samsung tab 2
- phone operating system version: Android 7.0
- version of lichess mobile:  6.1

**Comment by freefal** [comment]
Are you online when this happens? The chart will reflect puzzles solved offline once you come back online at which point your offline results will be sent to the server.

**Comment by joselo89** [comment]
Yes, it's happening to me too. I do tactics on my app, and the rating doesnt change.

**Comment by rwuwon** [comment]
This appears to be same as #813 and #831 (among other closed issues) which appeared to be resolved there, but has since returned?

I'm running lichess v6.1.0 on a 2016 Pixel with Android 9. Clearing storage does work as a workaround until I do puzzles in my desktop browser again so for now, I'm only doing puzzles from the mobile app.

**Comment by ChameleonRed** [comment]
> 
> 
> Are you online when this happens? The chart will reflect puzzles solved offline once you come back online at which point your offline results will be sent to the server.

@freefal I am always online when it happens (WiFi). Sometimes it is possible that from time to time connection is lost for 1s but I tested it near router and problem is the same.

**Comment by RowdyHowell** [comment]
I have the issue as well.  To give some more insight into what might be happening, here's a scenario that I've run:

1. Do training on my Android phone (eg. puzzle 77874)
2. Fail the training on my phone, no score updates
3. Do the same training (77874) on web
4. Pass the training and get +0 points and the training is not added to the history
5. Do another training on web
6. Pass, get +X points, training added to the history

I guess this makes it look like the training is registering with the server in some way.  If there's a scenario that would help debug what's going on let me know and I can run it.

**Comment by RowdyHowell** [comment]
According to [this Reddit thread](https://www.reddit.com/r/chess/comments/8gab9k/lichess_puzzle_rating_not_updating_on_android_app/) a reinstall fixes this issue.  Does it have something to do with local storage?  I do training on my phone and on my laptop frequently - maybe something becomes out of sync.

**Comment by rwuwon** [comment]
@RowdyHowell - A reinstall _should_ work as a temporary workaround *but* that's probably only because it clears storage (you can access this option via "App info", either by long-pressing the app icon, or going through settings and storage in Android). The issue will resurface as soon as you start doing puzzles on another device (e.g., desktop browser).

At the moment I simply reserve puzzles to my phone only to avoid this problem, and not worry about the puzzle rating or other details that one finds in the normal desktop browser mode (i.e., I just play the board as I see it and not worry about where the game comes from and who it was between).

**Comment by RowdyHowell** [comment]
Gotcha.  Does anybody know if this is reproducible in the browser version of the mobile app?  Seems like the best way of debugging - might take a stab at fixing it.

**Comment by ChameleonRed** [comment]
Reinstall should not help - something is broken with connection detection. Client should reload data from server if connection is reverted as soon as possible or every some minute to reduce traffic if connection is very bad.

I think that cleaning data will not help but I will try. I see problem after doing 1-2 puzzle first works but next stuck on chart and ranking. I was working perfectly one year ago.

**Comment by xcombelle** [comment]
I had the problem of not having score updated after solving a problem on lichess mobile app

I have not a very good connection on mobile.

An uninstall of lichess app and resinstall did not solved the problem

The problem number of the app was lagging a lot behind the problem number of site problem

deleting local data and cache data from android menu in the intend to solve the problem. It suceed.

I have no more this problem

Since the problem solved I did not used the site problems.

**Comment by ecomaikgolf** [comment]
Yesterday happened to me, counts as win but doesn't add elo:
![Screenshot](https://user-images.githubusercontent.com/8388874/64067259-1da9c680-cc26-11e9-891d-e91ff2df05f5.png)

**Comment by ChameleonRed** [comment]
It is still problem - I never use mobile application for puzzles since it is not usable. If I have to I use chrome to open lichess on mobile what is very battery draining.
