### ISSUE TITLE
after-game menu changes and causes misclicks

### ISSUE THREAD

**Issue by ornicar** [veloce/lichobile#917]
from an email:
```
 When the game ends a menu automatically pops up. This regularly causes me to accidentally request a rematch, pull up the share the pgn menu, etc. Also, when the opponent is no longer able to be challenged to a rematch, that option disappears on the menu, the menu is instantly changed into a shorter menu with all of the remaining buttons shifted slightly, and I regularly hit the wrong button as a result. 

When a game ends and the menu comes up, could all of the buttons be non-operational and greyed out for about one second to prevent accidental clicks? And could the full menu always be shown, simply disabling and greying out the rematch button when a rematch is no longer possible in order to prevent accidental clicks? Or any other solution that addresses these problems well.
```

**Comment by leonty** [comment]
That's really an issue. If we ever had statistics on the revanche offers, we'd see that probably half of them then cancelled. Just because that's where you mostly tip (the center of the board) and then suddenly the pop up menu arrives!
Another really annoying issue is that some menu items can disappear (for instance "accept the revanche offer) because something happens (the offer is cancelled from the other side) and the item is not relevant anymore. So I often misclick on the "share" because of that.

Making the menu inactive for a second after the game would solve the issue. Also menu items shoudn't change their positions after the menu is shown.

**Comment by leonty** [comment]
@veloce Please, clarify does this change affects both the issues: immediate pop up of the menu and the tossing menu items after being displayed?

**Comment by veloce** [comment]
yes, immediate popup is gone and rematch button doesn't disappear anymore when it's not available (it's greyed out)

**Comment by leonty** [comment]
Thank you.
