### ISSUE TITLE
App connectivity issue

### ISSUE THREAD

**Issue by arimourao** [veloce/lichobile#945]
# Bug report

**Current behavior:**

The app fails to asses that my phone is connected to the internet through a Wi-Fi connection. Then the only options shown are to start an offline game or Analysis board. This happened a lot, under different Wi-Fi connections and I'm pretty sure there wasn't any kind of internet connection issues, because I was able to browse webpages, watch streams on Youtube, and so on.

**Expected behavior:**

The app should correctly asses that Wi-Fi connection is up and running

**Steps to reproduce:**

This is a hard one to reproduce. It doesn't happen always. But when I turn off my wi-fi and turn it back on, it fixes temporarily the issue. It just happens after I lock the screen of my phone and the app is running in the background.

**Environment information**

- phone hardware: Motorola X1
- phone operating system version: Android 8.0
- version of lichess mobile: 6.1.1

**Comment by freefal** [comment]
I have had this issue as well. My workaround is to kill the app and restart it. If you find steps to reliably reproduce the issue, please let us know as that would be very helpful in developing a fix.

**Comment by WienerBrit** [comment]
I keep having this issue too. Including in the middle of the game. I show connected. My opponents clock runs down. Then *I* lose on time.

**Comment by WienerBrit** [comment]
I keep having this issue too. Including in the middle of the game. I show connected. My opponents clock runs down. Then *I* lose on time.

**Comment by vc7ee** [comment]
Same thing, happens on stable wifi and (this) also on stable 4G connections. https://sh.c7.ee/6usXx/Screenshot_20190612-143837.jpg
In this game, the opponent actually moved (ate my pawn). In fast-paced games I just don't have the time do kill the app.

**Comment by veloce** [comment]
https://github.com/apache/cordova-plugin-network-information/issues/64 could explain the problem.

**Comment by ilovelinux** [comment]
Same here

**Comment by P1ng-W1n** [comment]
I had the same issue on my Samsung Galaxy A5 (both on Wifi and on 4G), and it turned out that the actual issue wasn't related to connectivity (according to the firewall logs it was able to reach lichess.org and socket.lichess.org without any issue), but rather to UI visualization (meaning that it was able to connect to the server, check my network connectivity status and also my latency, but wasn't able to show non-static UI elements (mainly the ones that are downloaded from the internet, like latest puzzle, available game modes and so on..)
It seems to me that the issue happens when Chrome is disabled and your phone performs an "Application Optimization" (like the one it does after each update/upgrade). 
Enabling Chrome did solve the issue in my case.

**Comment by ilovelinux** [comment]
Crome disabled here too. I think it's related

**Comment by jnslmk** [comment]
I am experiencing the same issues on lineages with Chrome uninstalled and the system browser deactivated. Turning them back on/reinstalling them didn't help unfortunately

**Comment by arimourao** [comment]
I noticed that this bug seems to have be solved. Just strange that no pull request did mention this issue. I think it can be closed now.

**Comment by veloce** [comment]
I think it was fixed withhttps://github.com/veloce/lichobile/commit/ef71daf74bd7a24c9805983b88a77212e43db959
