### ISSUE TITLE
Request takeback problem

### ISSUE THREAD

**Issue by AdityaMH** [veloce/lichobile#987]
I request undo move to my opponent, and he accepted, but why takeback/undo move given to opponent, not me?
Then my opponent rejected my request after he steal my undo.
And why share url button not copied to my clipboard even clicked?

**Comment by jas14** [comment]
@AdityaMH, please fill out the [issue template](https://github.com/veloce/lichobile/blob/master/.github/issue_template.md) that appeared when you created this issue. We can't reproduce the bug if you don't provide more information, and we can't fix the bug if we can't reproduce it.

Also, this is two separate issues:
1. Move takeback is incorrectly switched
2. Share URL not copied to clipboard

Can you please file this as 2 separate issues?

**Comment by AdityaMH** [comment]
Ignore about Share URL not copied to clipboard, this problem happen because i not updated Drive to latest version.
But about takeback, this happen when:
 1. I want to move my queen to: (18. ... Qc8). but my hand slipped to Qb8 and my opponent move to (19. c3)
 2. I request to takeback, and my opponent accepted, but why only canceling move c3 not my queen? and going to his turn not my turn.
 3. I request to takeback again because this unwanted moment, but he always rejected because he take my queen.

And maybe you know what next happen.
https://lichess.org/SU2x3OTg

**Comment by freefal** [comment]
This is not an app-specific issue. The takeback mechanic on the Lichess server, with which both the website and app interface, is that a proposal applies to the most recent move at the time the takeback proposal is made.

You can file an issue for the server here (https://github.com/ornicar/lila), but I suspect that this is expected behavior. You need to either propose you takeback prior to your opponent moving or else send a second takeback request after he accepts the first.

**Comment by landry314** [comment]
This exact problem was discussed here, in the proper github page:
https://github.com/ornicar/lila/issues/2414

It was closed by a main programmer. I disagree with the closure and agree with @AdityaMH . You might want to voice your concerns there.

This is an annoying persistent problem for many years.
